# Generated by Django 5.0.4 on 2024-09-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='starggtournament',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
