# Generated by Django 5.0.4 on 2024-09-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_starggtournament_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallongeTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('idTournament', models.CharField(max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
