# Generated by Django 5.0.4 on 2024-09-16 15:33

import fighters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_challongetournament_flayer_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img_url', models.ImageField(upload_to='posts', validators=[fighters.models.Post.validate_image])),
            ],
        ),
        migrations.AlterField(
            model_name='challongetournament',
            name='flayer_img',
            field=models.ImageField(blank=True, upload_to='flayers/', validators=[fighters.models.ChallongeTournament.validate_image]),
        ),
    ]
