# Generated by Django 5.0.4 on 2024-09-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0005_post_alter_challongetournament_flayer_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='challongetournament',
            name='game_name',
            field=models.CharField(blank=True, max_length=70),
        ),
    ]
