# Generated by Django 5.0.4 on 2024-09-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0006_challongetournament_game_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='challongetournament',
            name='sign_up_url',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
