# Generated by Django 5.0.4 on 2024-09-18 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0008_challongetournament_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='challongetournament',
            name='stream_url',
            field=models.URLField(blank=True),
        ),
    ]
