# Generated by Django 5.0.4 on 2024-09-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0009_challongetournament_stream_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('platform', models.CharField(choices=[('TW', 'Twitch'), ('YT', 'YouTube'), ('FB', 'Facebook')], default='TW', max_length=2)),
            ],
        ),
    ]
