# Generated by Django 5.0.4 on 2024-09-23 22:45

import fighters.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0010_streamuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('event_img', models.ImageField(upload_to='event', validators=[fighters.models.EventSpecial.validate_image])),
                ('fecha', models.DateTimeField()),
                ('type_event', models.CharField(choices=[('ONLINE', 'Online'), ('PRESENCIAL', 'Presencial'), ('ONLINE_PRESENCIAL', 'Online-Presencial'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('tags', models.ManyToManyField(related_name='events', to='fighters.tag')),
            ],
        ),
    ]
