# Generated by Django 5.0.4 on 2024-09-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0011_tag_eventspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspecial',
            name='url_info',
            field=models.URLField(blank=True),
        ),
    ]
